remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/leap-day@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: just-the-docs/just-the-docs@v0.6.2
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one