name: Cleanup Badges Branch
on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force cleanup of badges branch'
        required: false
        default: 'false'
  schedule:
    - cron: 0 0 * * 1  # Run weekly

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: badges
          path: badges
      - name: Reset and create single commit
        run: |
          pushd badges
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git reset --soft $(git rev-list --max-parents=0 HEAD) && git commit --amend --date=now --no-edit
          git push --force origin badges
          popd